markdown:         kramdown
highlighter:      rouge
title:            Open Web Store
tagline:          Web apps are the future.
description:      "Web Store by Ubuntu Web"
url:              https://github.com/karloespiritu/blackdoc
baseurl:          /
paginate:         5
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-algolia
main:             https://ubuntu-web.github.io
github:
  repo:           https://github.com/Ubuntu-Web/ubuntu-web.github.io
